apps/registro/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns=[
	path(r'',views.createAtleta,name="registro"),
	path(r'listado/',login_required(views.atletasLista),name="listado_atletas"),
	path(r'listado/order_by_carrera/',login_required(views.order_by_carrera),name="listado_atletas_carerra"),
	path(r'listado/order_by_pay',login_required(views.order_by_pay),name="listado_atletas_pay"),
	path(r'cheking/',views.confirmacion_pago,name="cheking"),
	path(r'cheking_form/',views.check_form,name="check_form"),
	path(r'editar_atletas/(?P<pk>\d+)/$',views.atleta_edit.as_view(),name='editar_atleta'),
	path(r'borrar_atleta/(?P<pk>\d+)/$',views.atleta_delete.as_view(),name='delete'),
	path(r'pago_ticket/',views.pago_atrasado,name='pago_atrasado'),
	path(r'pago_ticket_validation/',views.validacion,name='validacion'),
	
	# path(r'^media_maraton/',views.registro_atleta_media,name="registro_atleta_media"),
	# path(r'^consulta/',views.consultar_atleta,name="consultar_atleta"),
	
]

media_maraton/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import  include,url
from django.contrib.auth.views import LoginView,logout_then_login
from . import views
urlpatterns = [
    path(r'',views.bienvenida,name="index"),
    path(r'registro/',include(("apps.registro.urls","registro"),namespace="registro")),
    path(r'accounts/login/', LoginView.as_view(template_name='autentication.html'),name="login"),
    path(r'salir/',logout_then_login,name="salir"),
	
]

apps/registro/models.py
from __future__ import unicode_literals

from django.db import models
import django.utils
import datetime

class atleta(models.Model):
	now = datetime.datetime.now()
	atleta_id = models.AutoField(primary_key=True)
	nombre_atleta=models.CharField(max_length=50)
	apellido_atleta=models.CharField(max_length=50)
	correo_atleta=models.EmailField()
	identificacion_atleta=models.CharField(max_length=50)
	edad_atleta=models.CharField(max_length=50)
	tipo_sangre_atleta=models.CharField(max_length=50)
	sexo_atleta=models.CharField(max_length=30)
	telefono_atleta=models.CharField(max_length=20)

	carrera_atleta=models.CharField(max_length=50,default="10k") ##PUEDE ELEGIR 10K O MEDIA MARATON 
	categoria_atleta=models.CharField(max_length=50,default=" ") ##PUEDE ELEGIR 10K O MEDIA MARATON 

	direccion_atleta=models.CharField(max_length=50)
	nacimiento_atleta=models.DateField(default= django.utils.timezone.now)
	talla_atleta=models.CharField(max_length=5,default="L")
	nombre_emergencia_atleta=models.CharField(max_length=30)
	telefono_emergencia_atleta=models.CharField(max_length=20)
	pago_confirmado=models.BooleanField(default=False)

	fecha_inscripcion =models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return '{} {}'.format(self.nombre_atleta,self.apellido_atleta)
	class Meta():
		ordering = ['-pago_confirmado']
	

apps/registro/forms.py
from django import forms
from apps.registro.models import atleta

from django.contrib.admin.widgets import AdminDateWidget

class atletaForm(forms.ModelForm):
	carrera_atleta=forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=(('','',),('Media Maraton', 'Media Maraton',),('10k', '10k',),('Silla De Ruedas', 'Silla De Ruedas',)))
	sexo_atleta=forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=(('Masculino', 'Masculino',), ('Femenino', 'Femenino',)))
	tipo_sangre_atleta=forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=(('A-','A+',),('B-','B+',),('O+', 'O+',), ('O-', 'O-',),('AB-','AB+',)))
	talla_atleta=forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=(('XS', 'XS',),('S', 'S',), ('M', 'M',),('L', 'L',),('XL', 'XL',)))
	
	class Meta:

		model=atleta
		


		fields=[
				'nombre_atleta',
				'apellido_atleta',
				'correo_atleta',
				'identificacion_atleta',
				'edad_atleta',
				'tipo_sangre_atleta',
				'sexo_atleta',
				'telefono_atleta',
				'carrera_atleta',
				'direccion_atleta',
				##'nacimiento_atleta',
				'talla_atleta',
				'nombre_emergencia_atleta',
				'telefono_emergencia_atleta',
				'categoria_atleta',
				
				
		]
		labels={
				'nombre_atleta':'Nombre',
				'apellido_atleta':'Apellido',
				'correo_atleta':'Correo Electronico',
				'identificacion_atleta':'Identificación',
				'edad_atleta':'Edad',
				'tipo_sangre_atleta':'Tipo De Sangre (RH)',
				'sexo_atleta':'Genero',
				'telefono_atleta:':'Numero Telefonico',
				'carrera_atleta':'Competencia',
				'direccion_atleta':'Direccion Residencial',
				##'nacimiento_atleta':'Fecha De Nacimiento',
				'talla_atleta':'Talla De Camisa',
				'nombre_emergencia_atleta':'En caso de emergencia llamar a : ',
				'telefono_emergencia_atleta':'Numero de tu contacto de emergencia',
				
				

		}
		widgets={
				
				'nombre_atleta': forms.TextInput(attrs={'class':'form-control'}),
				'apellido_atleta':forms.TextInput(attrs={'class':'form-control'}),
				'correo_atleta':forms.EmailInput(attrs={'class':'form-control'}),
				'identificacion_atleta':forms.TextInput	(attrs={'class':'form-control'}),
				'edad_atleta':forms.NumberInput(attrs={'class':'form-control'}),
				'telefono_atleta':forms.TextInput(attrs={'class':'form-control'}),
				'direccion_atleta':forms.TextInput(attrs={'class':'form-control'}),
				'nombre_emergencia_atleta':forms.TextInput(attrs={'class':'form-control'}),
				'telefono_emergencia_atleta':forms.TextInput(attrs={'class':'form-control'}),
				
								
		}

class atletaFormWithPay(forms.ModelForm):
	talla_atleta=forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=(('XS', 'XS',),('S', 'S',), ('M', 'M',),('L', 'L',),('XL', 'XL',)))
	categoria_atleta=forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}), choices=(('10k', '10k',), ('Media Maraton', 'Media Maraton',)))
	class Meta:

		model=atleta
		


		fields=[
				'nombre_atleta',
				'apellido_atleta',
				'edad_atleta',
				'correo_atleta',
				'identificacion_atleta',
				'categoria_atleta',
				'talla_atleta',
				
				
		]
		labels={

		      	'nombre_atleta': 'Nombre',
				'apellido_atleta':'Apellido',
				'edad_atleta':'Edad',
				'correo_atleta':'Correo Electronico',
				'identificacion_atleta':'Identificacion',
				'categoria_atleta':'Categoria',
				'talla_atleta':'Talla',
				
				

		}
		widgets={
				
				'nombre_atleta': forms.TextInput(attrs={'class':'form-control'}),
				'apellido_atleta':forms.TextInput(attrs={'class':'form-control'}),
				'edad_atleta':forms.NumberInput(attrs={'class':'form-control'}),
				'correo_atleta':forms.EmailInput(attrs={'class':'form-control'}),
				'identificacion_atleta':forms.TextInput	(attrs={'class':'form-control'}),
				

				
		}

apps/registro/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals



from django.shortcuts import render,redirect
from django.urls import reverse_lazy

from django.http import HttpResponse,HttpResponseRedirect

from django.views.generic import ListView, UpdateView, CreateView, DeleteView
	
from apps.registro.forms import atletaForm,atletaFormWithPay

from apps.registro.models import atleta
from django.http import JsonResponse

from django.views.decorators.csrf import csrf_exempt

from django.core.mail import send_mail

import hashlib 


def conteo():
	return(atleta.objects.filter(carrera_atleta="Media Maraton",pago_confirmado=True).count(),atleta.objects.filter(carrera_atleta="10k").count()+100,atleta.objects.filter(carrera_atleta="Media Maraton").count(),atleta.objects.filter(carrera_atleta="Silla De Ruedas").count())

def enviar_correo(correo,nombre,carrera,categoria):
	categoria_atleta=categoria.upper()
	fecha_carrera='ABRIL 7 2019'
	nombre_atleta=nombre.upper()
	competencia_atleta=carrera.upper()
	text='<div style="background-image: url'+"('https://mediavillavicencio.herokuapp.com/static/images/banner2.jpg')"+';background-repeat: no-repeat;background-attachment: absolute; background-position:center;position:relative;top:0;left:0;right:0">'+'<div style="background-color:rgba(0,0,0,0.7);font family'+":'Verdana';margin:10%;padding:10%;color:"+'white">'+'<h1 style="text-align: center"> Hola '+nombre_atleta+'</h1>'+" "+'<h2 style="text-align:center;color: #f2f2f2">'+'TU INSCRIPCIÓN A LA <span style="color:#428bca">'+competencia_atleta+'</span> A CELEBRARSE EN LA CIUDAD DE VILLAVICENCIO EL <span style="color:#5cb85c">'+ fecha_carrera +'</span> EN LA CATEGORÍA <span style="color:#5cb85c">'+categoria_atleta+'</span> FUE <span style="color:#d9534f"> COMPLETADA EXITOSAMETE </span> </h2><h1><img src="http://www.villavicencio.gov.co/Style%20Library/images/logo-alcaldia.png"></h1></div></div>'
	send_mail(
    'Inscripción Completada '+competencia_atleta+' Ciudad De Villavicencio',
    '',
    'mediamaratonvillavicencio@gmail.com',
    [correo],
    fail_silently=False,
    html_message=text,
	)

def enviar_correo2(correo,nombre,carrera,categoria):
	categoria_atleta=categoria.upper()
	fecha_carrera='ABRIL 7 2019'
	nombre_atleta=nombre.upper()
	competencia_atleta=carrera.upper()
	text='Nuevo Corredor: '+nombre_atleta+' Carrera: '+competencia_atleta+' Categoria: '+categoria_atleta
	send_mail(
    'Inscripción Completada---> '+nombre_atleta,
    '',
    'mediamaratonvillavicencio@gmail.com',
    [correo],
    fail_silently=False,
    html_message=text,
	)



def createAtleta(req):
	if req.method=='POST':
			correo=req.POST.get('correo_atleta')
			cedula=req.POST.get('identificacion_atleta')
			nombre=req.POST.get("nombre_atleta")+' '+req.POST.get("apellido_atleta")
			categoria=req.POST.get('categoria_atleta')
			carrera=req.POST.get('carrera_atleta')
			if(atleta.objects.filter(correo_atleta=correo).exists()):
				return JsonResponse({'alerta':'Correo Registrado previamente'})
			else:	
				valor=40000
				api="o6y7ENS2dxTgm9a5I78SwTz8OZ"
				merchan="789496"
				referencia=cedula
				currency="COP"
				string_signature=""+api+"~"+merchan+"~"+referencia+"~"+str(valor)+"~COP"
				code = hashlib.md5()
				code.update(string_signature.encode())
				firma=code.hexdigest()
				form =atletaForm(req.POST)
				if form.is_valid():
					form.save()
				if (carrera=='10k' or carrera=='Silla De Ruedas'):
					enviar_correo(correo,nombre,'carrera '+carrera,categoria)
					enviar_correo2("mediamaratonvillavicencio@gmail.com",'Nuevo Corredor'+nombre,'carrera '+carrera,categoria)
					return render(req,"inscripcion_libre.html",{'nombre':nombre})
				else:		
					return render(req,"pago.html",{'categoria':categoria,'correo':correo,'nombre':nombre,'signature':firma,'ref':referencia,'valor':valor,'cedula':req.POST.get('identificacion_atleta')})
	else:
		form=atletaForm()
	
	return render(req,"registro.html",{'form':form})	


class atleta_delete(DeleteView):
	model=atleta
	template_name="atleta_delete.html"
	success_url= reverse_lazy('registro:listado_atletas')




def atletasLista(req):
		
		if (req.user.username=='Wilder_Herrera'):
			if not ('order_name' in req.session):
				req.session['order_name']=False

			
			if(req.session['order_name']):
					object_list=atleta.objects.all().order_by('-nombre_atleta')
					req.session['order_name']=not(req.session['order_name'])	
			else:
					object_list=atleta.objects.all().order_by('nombre_atleta')
					req.session['order_name']=not(req.session['order_name'])	
			check_pay,t10k,tmm,tsr=conteo()
			
			return(render(req,"listado_atletas.html",{'object_list':object_list,'pago':check_pay,'total_10k':t10k,'total_mm':tmm,'total_sr':tsr}))

		elif (req.user.username=='IMDER'):
			check_pay,t10k,tmm,tsr=conteo()
			return(render(req,"listado_atletas.html",{'total_10k':t10k,'total_mm':tmm,'total_sr':tsr}))
		else:
			return JsonResponse({'user':'no available'})


def order_by_carrera(req):

	if (req.user.username=='Wilder_Herrera'):
		if not ('order_carrera' in req.session):
			req.session['order_carrera']=False
		
		if(req.session['order_carrera']):
				object_list=atleta.objects.all().order_by('-carrera_atleta')

				req.session['order_carrera']=not(req.session['order_carrera'])	

		else:
				object_list=atleta.objects.all().order_by('carrera_atleta')

				req.session['order_carrera']=not(req.session['order_carrera'])	

		check_pay,t10k,tmm,tsr=conteo()
		return(render(req,"listado_atletas.html",{'object_list':object_list,'pago':check_pay,'total_10k':t10k,'total_mm':tmm,'total_sr':tsr}))
	else:
		return JsonResponse({'user':'no available'})

def order_by_pay(req):
	
	if (req.user.username=='Wilder_Herrera'):	
		if not ('order_pay' in req.session):
			req.session['order_pay']=False

		
		if(req.session['order_pay']):
				object_list=atleta.objects.all().order_by('pago_confirmado')

				req.session['order_pay']=not(req.session['order_pay'])	

		else:
				object_list=atleta.objects.all().order_by('-pago_confirmado')

				req.session['order_pay']=not(req.session['order_pay'])		


		check_pay,t10k,tmm,tsr=conteo()
		return(render(req,"listado_atletas.html",{'object_list':object_list,'pago':check_pay,'total_10k':t10k,'total_mm':tmm,'total_sr':tsr}))
	else:
		return JsonResponse({'user':'no available'})


@csrf_exempt 
def confirmacion_pago(req):
	if(int(req.POST.get("state_pol")) ==4 and req.POST.get("response_message_pol")=="APPROVED") :	
		atleta_query=atleta.objects.filter(identificacion_atleta=req.POST.get("extra1"))
		atleta_query.update(pago_confirmado=True)
		email=(req.POST.get('email_buyer'))
		nombre=(atleta_query.values('nombre_atleta')[0]['nombre_atleta'])
		categoria=(req.POST.get('extra2'))##Categoria
		carrera=atleta_query.values('carrera_atleta')[0]['carrera_atleta']
		enviar_correo(email,nombre,carrera,categoria) ###PONER DATOS FUNCION EMAIL
		print ("Pago Confirmado")


	return (HttpResponse(status=200))



def check_form(req):
	correo=req.GET.get("correo")
	cedula=req.GET.get("cedula")
	identificacion_msg=""
	correo_msg=""


	if atleta.objects.filter(correo_atleta=correo).exists():
		correo_msg="El correo electronico ya fue registrado"
	elif len(correo)==0:
		 correo_msg="Ingrese un correo electronico"
	else:
		correo_msg="undefined"

	if atleta.objects.filter(identificacion_atleta=cedula).exists() :
		identificacion_msg="La identificacion ya fue registrada"

	elif len(cedula)==0:
		 identificacion_msg="Ingrese un numero de identificacion"
	else: 
		identificacion_msg="undefined"

	return JsonResponse({"cedula":identificacion_msg,"correo":correo_msg})

class atleta_edit(UpdateView):
	model=atleta
	template_name="atleta_edit.html"
	form_class=atletaFormWithPay
	success_url= reverse_lazy('registro:listado_atletas')


class atletaDelete(DeleteView):
    model = atleta
    success_url = reverse_lazy('registro:listado_atletas')


def pago_atrasado(req):
	if (req.method=='GET'):
		return render(req,'pago_atrasado.html')

	else:
		print("aqui")
		cedula=req.POST.get('cedula')
		atleta_query=atleta.objects.filter(identificacion_atleta=cedula)
		nombre=(atleta_query.values('nombre_atleta')[0]['nombre_atleta'])
		carrera=atleta_query.values('carrera_atleta')[0]['carrera_atleta']
		correo=atleta_query.values('correo_atleta')[0]['correo_atleta']
		categoria=atleta_query.values('categoria_atleta')[0]['categoria_atleta']
		valor=40000
		api="o6y7ENS2dxTgm9a5I78SwTz8OZ"
		merchan="789496"
		referencia=cedula
		currency="COP"
		string_signature=""+api+"~"+merchan+"~"+referencia+"~"+str(valor)+"~COP"
		code = hashlib.md5()
		code.update(string_signature.encode())
		firma=code.hexdigest()
		return render(req,"pago.html",{'categoria':categoria,'correo':correo,'nombre':nombre,'signature':firma,'ref':referencia,'valor':valor,'cedula':cedula})

@csrf_exempt 
def validacion(req):
		cedula=req.POST.get('cedula')
		if (atleta.objects.filter(carrera_atleta="Media Maraton",identificacion_atleta=cedula).exists()):
			return JsonResponse({'validacion':'existe'})
		else:
			return JsonResponse({'validacion':'No registrado'})

templates/atleta_delete.html
{% extends 'index.html' %}
{% block header%}
{% endblock %}
{% block banner%}
{% endblock%}

{% block content %}
<div class="col-md-12 text-center p-5">	
	<h2>Borrar atleta</h2>
	<h5 class="m-5"> Seguro quieres eliminar al atleta: </h5>
	<form method="POST">
		{% csrf_token %}
		{{object.nombre_atleta}} {{object.apellido_atleta}}
		<hr>
		<button type="submit" class="btn btn-outline-danger"> Borrar</button>
		<a href="{% url 'registro:listado_atletas'%}" class="btn btn-outline-success"> No borrar</a>
	</form>
</div>
{% endblock %}

templates/atleta_edit.html
{% extends 'index.html' %}
{% block banner %}
{% endblock %}
{% block content %}
<div class="container m-5 p-5" style="background-color: #f2f2f2f2">
	<div class="row">
		<div class="col-md-12  text-center ">
				<h3 class="text-uppercase"><span class="fa fa-user"></span> Edicion de atletas</h3>
		</div>

		<div class="col-md-10 mt-5 offset-md-1 text-left">
			{% if form %}
				<form class="form" method="POST" >
					{% csrf_token %}
				<table class="table">
				<tr>
					<td><h5>Nombre</h5>
					{{form.nombre_atleta}}</td>
					<td><h5>Apellido</h5>
					{{form.apellido_atleta}}</td>
				</tr>
				<tr>
					<td><h5>Edad</h5>
					{{form.edad_atleta}}</td>
					<td><h5>Correo Electronico</h5>
					{{form.correo_atleta}}
					<p id="alerta_correo" style="color:red"></p>
				</td>
					
				
					
				</tr>
				<tr>
					<td><h5>Identificacion</h5>	
					{{form.identificacion_atleta}}
				<p id="alerta_cedula" style="color:red"></p></td>
					
					<td><h5>Categoria</h5>
					{{form.categoria_atleta}}</td>

					<td><h5>Talla Atleta</h5>
					{{form.talla_atleta}}</td>
				</tr>
				</table>
				<br>
					<div class="text-center">
					<button type="submit" class="btn btn-lg btn-primary mt-6 animated pulse infinite" id="boton-registro">Editar</button>
					</div>
				</form>
			{% endif %}
				
				
				
		</div>	
	</div>
</div>
{% endblock %}

templates/errorform.html
{% extends 'index.html'%}
<h1>Error de formulario</h1>

templates/listado_atletas.html
{% extends 'index.html' %}
{% block header%}
{% load staticfiles %}
<header id="mobil_head">
	<div class="container-fluid bg-success">
		<div class="col-md-12 bg-info p-2"></div>
			<nav class="pt-md-4 d-lg-flex" style="border-bottom: 3px solid black;background-color:rgba(51,255,50,0.9);padding-right:5%;padding-left:5%;">

			<div class="col-md-5">
					<div id="logo">
						<a href="{% url 'index'%}"><img src="{% static 'images/logo.png'%}" width="35%"></a>
						<h3 class="mb-3 text-left" style="color:#f2f2f2;font-weight: bold"> ABRIL 7 2019 </h3>
						<!-- <h3> <a href="{% url 'index'%}"><span style="color:#006600"><strong>MEDIA</strong></span>  MARATÓN<span class="text-danger" style="font-weight: bold"> VILLAVICENCIO</span></a> <br> </h3> -->			
					</div>
			</div>

			<div class="col-md-7 text-right"> 
				<div id="logo_header">
							<a href="https://www.imdervillavicencio.gov.co"><img data-aos="flip-left" data-aos-duration="1000" src="{% static 'images/logo_imder.png'%}" width="15%"  class="img-fluid rounded" style="background-color: #f2f2f2"></a>		
							<a href="http://www.coc.org.co/national-federations/federacion-colombiana-de-atletismo/"><img data-aos="flip-left" data-aos-duration="1000" src="{% static 'images/Logo_alcaldia.png'%}" width="15%"  class="img-fluid rounded" style="background-color: #f2f2f2"></a>
							<a href="http://www.coc.org.co/national-federations/federacion-colombiana-de-atletismo/"><img data-aos="flip-left" data-aos-duration="2000" src="{% static 'images/logo_federacion.png'%}" width="17%" class="img-fluid rounded" style="background-color: #f2f2f2"></a>
							<a href="http://www.coc.org.co/national-federations/federacion-colombiana-de-atletismo/"><img data-aos="flip-left" data-aos-duration="3000" src="{% static 'images/Logo_liga_2.png'%}" width="14%" class="img-fluid rounded" style="background-color: #f2f2f2"></a>
				</div>
					
						<ul class=" mt-lg-1 text-left" id="main_menu">	
						<div class=" col-md-12 p-1 mt-1 bg-info">
							</div>
						<li class="active"><a  href="{% url 'index'%}"><span class="fa fa-home blue_icon text-dark"></span>  Inicio</a></li>
						<li class="text-info">|</li>
						<li><a href="{% url 'registro:registro' %}"><span class="fas fa-sign-in-alt blue_icon text-dark "></span> Inscripción</a></li>
						<li class="text-info">|</li>
						
						<li><a href="{% url 'registro:listado_atletas' %}"><span class="fa fa-user-shield blue_icon text-dark"></span> 
						Ver Atletas</a></li>
						</ul>		
							
			</nav>		
		</div>
	</div>	
</header>

<header id="mobil_head_2">
	<div class="container" style="border-bottom: 3px solid black;background-color: rgba(53,173,30,0.9);padding-left:5%;">
		<div class="row">
			<div class="col-sm-6 text-center">
					
						<a href="{% url 'index'%}"><img src="{% static 'images/logo.png'%}" width="35%"></a>
						<h4 style="color:#f2f2f2;font-weight: bold"> ABRIL 7 2019 </h4>
						<!-- <h3> <a href="{% url 'index'%}"><span style="color:#006600"><strong>MEDIA</strong></span>  MARATON<span class="text-danger" style="font-weight: bold"> VILLAVICENCIO</span></a> <br> </h3> -->	
										<div id="logo_header" class="pb-2">
								<a href="http://www.coc.org.co/national-federations/federacion-colombiana-de-atletismo/"><img data-aos="flip-left" data-aos-duration="1000" src="{% static 'images/Logo_alcaldia.png'%}" width="15%"  class="img-fluid rounded" style="background-color: #f2f2f2"></a>
								<a href="http://www.coc.org.co/national-federations/federacion-colombiana-de-atletismo/"><img data-aos="flip-left" data-aos-duration="2000" src="{% static 'images/logo_federacion.png'%}" width="17%" class="img-fluid rounded" style="background-color: #f2f2f2"></a>
								<a href="http://www.coc.org.co/national-federations/federacion-colombiana-de-atletismo/"><img data-aos="flip-left" data-aos-duration="3000" src="{% static 'images/Logo_liga_2.png'%}" width="14%" class="img-fluid rounded" style="background-color: #f2f2f2"></a>
						</div>		
			
		
				</div>
		<nav class="d-lg-flex text-right"  style="position: fixed;float: left">
			<label for="drop" class="toggle bg-primary" ><span class="fa fa-bars "></span></label>
			<input type="checkbox" id="drop" />
			<ul class="menu mx-5 mt-lg-4 ml-auto" style="background-color: transparent;">
								<li><a  href="{% url 'index'%}"><span class="fa fa-home blue_icon text-dark"></span>  Inicio</a></li>					
			</ul>
		</nav>
			</div>
		</div>
</header>

{% endblock %}

{% block banner %}
{% endblock %}
{% block content %}
<style type="text/css">
	body{background-color: #303030}
</style>
<div class="container-fluid my-5 py-5" style="background-color: #f2f2f2f2">
	<div class="row">
		<div class="col-md-12 text-center">
				<h1 class="mb-4"><span class="fa fa-user"></span> Atletas Registrados</h1>
				<div class="text-left">
				<h4 class="p-1"> Total 10k= {{total_10k}}</h4>
				<h4 class="p-1"> Total Media= {{total_mm}}</h4>  
				{% if pago %}
				<h4 class="p-1"> Total Media Confirmados= {{pago}}</h4>  
				{% endif %}
				<h4 class="p-1"> Total Silla de ruedas= {{total_sr}}</h4>

				</div>
				{% if object_list %}
				<table class="table" >
					<tr class="text-left" id="headlines_atletas">
						
						<td>Nombre <a href="{% url 'registro:listado_atletas' %}"><span class="fa fa-sort"></span></a></td>
						<td>Edad</td>
						<td>Telefono</td>
						<td>Carrera <a href="{% url 'registro:listado_atletas_carerra' %}"><span class="fa fa-sort"></span></a></td>
						<td>Categoria</td>
						<td>Correo</td>
						<td>Identificacion</td>
						<td>Fecha De Registro</td>
						<td>Pago Confirmado <a href="{% url 'registro:listado_atletas_pay' %}"><span class="fa fa-sort"></span></a></td>
						<td></td>
						<td></td>
						
						

					</tr>
					
					
					{% for atleta in object_list%}
					<tr class="text-left">
						
						<td>{{ atleta.nombre_atleta }} {{ atleta.apellido_atleta }}</td>
						<td>{{ atleta.edad_atleta }}</td>
						<td>{{ atleta.telefono_atleta }}</td>
						<td>{{ atleta.carrera_atleta}}</td>
						<td>{{ atleta.categoria_atleta}}</td>
						<td>{{ atleta.correo_atleta}}</td>
						<td>{{ atleta.identificacion_atleta}}</td>
						<td>{{atleta.fecha_inscripcion}}</td>
						{% if atleta.pago_confirmado %}
						<td>Si</td>
						{% else %}
						<td>No</td>
						{%endif%}

						<td> <a class="btn btn-success" href="{% url 'registro:editar_atleta' atleta.atleta_id %}"> Editar</button></td>
						<td> <a class="btn btn-danger" href="{% url 'registro:delete' atleta.atleta_id %}"> Borrar</button></td>				
					    <!--  -->
					{% endfor %}
					{% endif %}
					</tr>
				</table>
				<div class="text-center">
					<a href="{% url 'salir' %}" class="btn btn-lg btn-danger">Cerrear Sesion</a>
					
				</div>
		</div>
	</div>
</div>
<style type="text/css">
	td{font-size: 10pt}
</style>
{% endblock %}